spring.application.name=cloudservice
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/cloudinfo
spring.datasource.username=dbuser
spring.datasource.password=dbpassword
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=quizapp
spring.rabbitmq.username=quizmail
spring.rabbitmq.password=quizmail123
custom.rabbitmq.mail_queue=mail
custom.rabbitmq.exchange=quizapp.exchange
custom.rabbitmq.routing_key=mail.send