spring.application.name=quiz
spring.data.mongodb.uri=mongodb://127.0.0.1/quiz
spring.data.mongodb.auto-index-creation=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=quizapp
spring.rabbitmq.username=quizapp
spring.rabbitmq.password=quizapp123
custom.security.unrestricted=/hello,/resetPassword,user/create,/user/getUserDetails,/user/login, /mail/send
custom.rabbitmq.mail_queue=mail
custom.rabbitmq.exchange=quizapp.exchange
custom.rabbitmq.routing_key=mail.send